<div class=container>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Váš účet</h1>
      <p class="lead">Děkujeme za to, že využíváte naše služby.</p>
    </div>
  </div>
  <ul class="list-group">
    <li class="list-group-item">Jméno: <?= $_SESSION['user']['name'] ?> </li>
    <li class="list-group-item">Příjmení: <?= $_SESSION['user']['surname'] ?></li>
    <li class="list-group-item">Email: <?= $_SESSION['user']['email'] ?></li>
  </ul>

</div>