<?php require "/opt/lampp/htdocs/4IZ278/app/model/adminusers.php" ?>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Jméno</th>
      <th scope="col">Příjmení</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>

    <?php foreach ($users as $user) : ?>
      <tr>
        <th scope="row">1</th>
        <td><?= $user['name'] ?></td>
        <td><?= $user['surname'] ?></td>
        <td><?= $user['email'] ?></td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>