<div class="container">
  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <span title="a Adam Jedlička">Zuzana Drozdová</span>
        <small class="d-block mb-3 text-muted">© 2020</small>
      </div>
      <div class="col-6 col-md">
        <h5>Služby</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Operace</a></li>
          <li><a class="text-muted" href="#">Preventivní péče</a></li>
          <li><a class="text-muted" href="#">Ošetření vrhů</a></li>
          <li><a class="text-muted" href="#">Prodej léčiv</a></li>
          <li><a class="text-muted" href="#">Prodej krmiv</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Ordinace</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Vybavení</a></li>
          <li><a class="text-muted" href="#">Veterinární lékařky</a></li>
          <li><a class="text-muted" href="#">Otevírací doba</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>O nás</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Historie</a></li>
          <li><a class="text-muted" href="#">Kontakt</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>