<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Zvěrolékařství Bolevec</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="/4IZ278/public/?page=eshop">Eshop</a>
    <a class="p-2 text-dark" href="/4IZ278/public/?page=cart">Košík</a>
    <a class="p-2 text-dark" href="/4IZ278/public/?page=orders">Moje objednávky</a>
    <a class="p-2 text-dark" href="/4IZ278/public/?page=account">Účet</a>
    <a class="p-2 text-dark" href="/4IZ278/app/model/logout.php">Odhlásit se</a>
  </nav>
</div>