<section class="u-clearfix u-section-1" id="sec-e60e">
  <div class="u-clearfix u-sheet u-sheet-1">
    <p class="u-text u-text-default u-text-1">Košík</p>
    <a href="#" class="u-btn u-btn-rectangle u-button-style u-palette-4-base u-btn-1">Objednat zboží</a>
    <p class="u-text u-text-default u-text-2">Položky:</p>
    <div class="u-container-style u-expanded-width u-grey-5 u-group u-group-1">
      <div class="u-container-layout u-container-layout-1">
        <img src="images/default-image.jpg" alt="" class="u-image u-image-default u-image-1" data-image-width="2000" data-image-height="1333">
        <p class="u-text u-text-default u-text-3">Název Produktu:</p>
        <p class="u-text u-text-default u-text-4">Granule pro psa</p>
        <p class="u-text u-text-default u-text-5">Počet<br>
        </p>
        <p class="u-text u-text-default u-text-6">2</p>
        <p class="u-text u-text-default u-text-7">Cena za kus<br>
        </p>
        <p class="u-text u-text-8">235&nbsp;</p>
        <p class="u-text u-text-default u-text-9">Celková cena<br>
        </p>
        <p class="u-text u-text-default u-text-10">235&nbsp;</p>
        <p class="u-text u-text-default u-text-11">Skladem<br>
        </p>
        <p class="u-text u-text-12">Ano</p>
        <a href="#" class="u-btn u-button-style u-palette-2-base u-btn-2">Odstranit</a>
      </div>
    </div>
  </div>
</section>